language: go
go: "1.11"
script:
  - GOOS=linux go build -o $GOPATH/bin/sync2confluence ./cli/sync2confluence
  - GOOS=darwin go build -o $GOPATH/bin/sync2confluence.mac ./cli/sync2confluence
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file:
    - "$GOPATH/bin/*"
  skip_cleanup: true
  on:
    tags: true
